### ISSUE TITLE
time_input causes error on Drupal data entry form (possibly Drupal 8 related)

### ISSUE THREAD

**Issue by andrewvanbreda** [Indicia-Team/client_helpers#120]
When setting up a text input with the Default Control Type set to time_input in the Warehouse survey attribute settings, I see the follow error on the Drupal data entry form

"TypeError: undefined is not an object (evaluating '$.browser.mozilla')"

(Note: this even occurs on other browsers such as Safari, it still says mozilla)

I am wondering if this is Drupal 8 related, seems to be ok in iRecord (which is Drupal 7 at time of writing) where the little arrow icon next to the field are correctly shown.
Going to leave as simple textbox on current project as it isn't worth the budget for me to fix.

**Comment by andrewvanbreda** [comment]
Actually, this might be because timeentry jQuery plugin isn't installed, not sure, will close this for now and reopen as required

**Comment by johnvanbreda** [comment]
I think I've setup time inputs before where I just used a text_input with the regex validation on the attribute so it is forced to hh:mm format. 
It's quite likely that I'll re-code the actual time_input to a html5 input with type="time" at some point, rather than use a library. That matches what we've done with dates. However for Safari we'll need a Polyfill or alternative at this point.

**Comment by andrewvanbreda** [comment]
@johnvanbreda 
OK thanks, yes that is good idea, we can live without the arrows that go with the time_input
